services:
  mongodb:
    image: mongo:8
    container_name: student-mongodb
    ports:
      - "27018:27017"

  student-registration-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-registration-app
    ports:
      - "5001:5000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/student_db
      SECRET_KEY: mysecretkey
    depends_on:
      - mongodb
